# Generated by Django 3.0.5 on 2020-08-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_titles_genres_categories', '0001_initial'),
        ('api_comments_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api_titles_genres_categories.Titles'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
